hcom/base/urls.py
from django.urls import path

from . import views

app_name = 'base'
urlpatterns = [
    path('', views.index, name='site-home'),
]

hcom/clinic/urls.py
from django.urls import path

from . import views


app_name = 'clinic'
urlpatterns = [
    path('', views.ClinicListView.as_view(), name='clinic-home'),
    path('<int:id>/', views.Clinic_Detail, name="clinic-detail"),
]

hcom/hcom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from rest_framework import routers
from users.forms import UserLoginForm
from users.views import UserViewSet

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('', include('base.urls')),
    path('auth/login/',
         auth_views.LoginView.as_view(template_name="users/user_login.html"),
         name='user-login'),
    path('clinic/', include('clinic.urls')),
    path('users/', include('users.urls')),
    path('pharmacy/', include('pharmacy.urls')),
    path('admin/', admin.site.urls),
    path('rest/', include(router.urls)),
    path('dummy/', include('dummy.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
           )  # To serve image correct paths in DEBUG MODE

hcom/pharmacy/urls.py
from django.urls import path
from .views import (
    DrugListView,
)

app_name = 'pharmacy'

urlpatterns = [
    path('', DrugListView.as_view(), name='drug-list')
]

hcom/users/urls.py
from django.urls import path

from .views import (LoadData, UserCreateView, UserDeleteView, UserDetailView,
                    UserListView, UserUpdateView)

app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='user-list'),
    path('user-list/', LoadData),
    path('add/', UserCreateView.as_view(), name='new-user'),
    path('<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('edit/<int:pk>/', UserUpdateView.as_view(), name="edit-user"),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name="delete-user"),
]

hcom/base/models.py
from django.db import models

# Create your models here.

hcom/base/views.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from django.shortcuts import render

# Create your views here.


def index(request):
    """
    Returns the basic home page of the HCOM web app.
    """
    return render(request, 'base/index.html')

hcom/templates/hcom/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Favicon -->
	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}"/>
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}"/>
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}"/>
	<link rel="manifest" href="{% static 'site.webmanifest' %}"/>

	<!-- Fontawesome files -->
	<link href="{% static 'css/all.min.css' %}" rel="stylesheet" />

	<!-- DataTables css -->
	<link href="{% static 'css/datatables.min.css' %}" rel="stylesheet" />

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

	<!-- Title -->
	{% if title %}
	<title>HCOM - {{ title }}</title>
	{% else %}
	<title>HCOM</title>
	{% endif %}
    </head>

    <body>

	<!-- Site Header -->
	<header>
	    <nav class="navbar navbar-expand-md navbar-dark bg-primary mb-3">
		<div class="container">
		    <a class="navbar-brand" href="{% url 'base:site-home' %}">HCOM</a>
		    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#MainNavbarMenu">
			<span class="navbar-toggler-icon"></span>
		    </button>
		    <div id="MainNavbarMenu" class="collapse navbar-collapse">
			<div class="navbar-nav me-auto">
			    <!-- Menu for system staff users -->
			    {% if user.is_staff %}
			    <a class="nav-link" href="{% url 'users:user-list' %}">Users</a>
			    {% endif %}
			    <!-- End of Menu for system staff users -->
			    <a class="nav-link" href="{% url 'clinic:clinic-home' %}">Clinic</a>
			    <a class="nav-link" href="{% url 'pharmacy:drug-list' %}">Pharmacy</a>
			    <a class="nav-link" href="{% url 'dummy:dummy-list' %}">Dummy</a>
			    <a class="nav-link" href="#">Contact Us</a>
			</div>
			<div class="navbar-nav">
			    {% if user.is_authenticated %}
			    <a class="nav-link" href="#">{{ user.username }}</a>
			    {% else %}
			    <a class="nav-link" href="#">Sign In</a>
			    {% endif %}
			</div>
		    </div>
		</div>
	    </nav>
	</header>

	<!-- Site content -->
	<div class="container">
	    {% block content %}
	    {% endblock content %}
	</div>

	<!-- Site Footer -->
	<footer class="bg-primary text-justify text-light py-3 px-3 fixed-bottom">
	    <div class="container">
		The contents of HCOM are copyrighted.
	    </div>
	</footer>

	<!-- Scripts -->

	<!-- JQuery -->
	<script src="{% static 'js/jquery-3.6.2.min.js' %}"></script>

	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

	<!-- Datatables -->
	<script src="{% static 'js/datatables.min.js' %}"></script>
	{% block scripts %}{% endblock scripts %}

    </body>

</html>

hcom/templates/hcom/modal.html
<div class="modal-dialog modal-xl">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title" id="theModalTitle"></h3>
            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body" id="theModalBody"></div>
        <div class="modal-footer">
            <a href="#" class="btn btn-secondary" data-bs-dismiss="modal" id="theModalButtonCancel">
                Cancel
            </a>
            <input class="btn btn-primary" type="button" value="" id="theModalButtonSubmit" />
        </div>
    </div>
</div>